# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navagiscore', '0002_auto_20180114_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='shapefiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('uploaded_date', models.CharField(default='', max_length=50)),
                ('uploaded_time', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='processing', max_length=50)),
                ('download_link', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
